# Generated by Django 5.0.2 on 2025-11-06 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Funcionário',
                'verbose_name_plural': 'Perfis de Funcionários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Idade do funcionário', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('salary', models.DecimalField(decimal_places=2, help_text='Salário mensal em EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('commute_time', models.IntegerField(help_text='Tempo de deslocamento diário em minutos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('gym_usage', models.IntegerField(help_text='Dias por mês usando academia', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('meal_voucher', models.DecimalField(decimal_places=2, help_text='Valor mensal do vale-refeição em EUR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('health_plan_tier', models.IntegerField(choices=[(1, 'Básico'), (2, 'Padrão'), (3, 'Premium')], default=2, help_text='Nível do plano de saúde')),
                ('satisfaction_score', models.FloatField(help_text='Score de satisfação previsto (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Previsão',
                'verbose_name_plural': 'Previsões',
                'ordering': ['-created_at'],
            },
        ),
    ]
